### ISSUE TITLE
Feature Request:  Add Exhaustion on first failed death save while unconscious

### ISSUE THREAD

**Issue by thepting** [ReAcTiOnN77/combat-exhaustion#2]
Love the module, was wondering if you'd be open to a feature request to add another mode that only adds exhaustion the first time a player misses a death saving through (for a single time going unconscious).

**Comment by ReAcTiOnN77** [comment]
Hi, thanks for the feedback. Glad you like the module.
Got a couple of questions.

Is that in addition to the other options? Or do you want it to work along side an option?

Not sure if that explains it well enough. But an checkbox on top of the 3 modes that also adds exhaustion on first death fail? 
Or a 4th option to implement on death fail?

**Comment by thepting** [comment]
I was thinking alongside as another option, but I don't know how you'd prefer to incorporate this with the "in combat" / "after combat" options you already have.

Basically, it's a "slightly milder" version of what you already have in that the players can avoid the exhaustion point if they are quick enough at healing the downed player and do it before the player misses a death save.  The way I play it I have the exhaustion point hit immediately (so I wouldn't do the "after combat" mode, though I guess maybe other DMs might).

One of the things I really liked about PF2e was that going down in the middle of combat had negative consequences, but 5e players are kind of skittish about it.  This felt like a happy medium for my campaigns, so I've been running this set of rules for a while.  But having trouble remembering to apply it in the middle of combat!

Thanks for listening and considering this, and for the module even if you don't want to implement it.

**Comment by ReAcTiOnN77** [comment]
Thanks for the response. I think I have an idea of how to implement it. I'll keep you posted.

**Comment by ReAcTiOnN77** [comment]
I have now implemented that feature and is available in new release

**Comment by ReAcTiOnN77** [comment]
Implemented Feature
